
// This file has been generated by the GUI designer. Do not modify.
namespace Graphs
{
	public partial class MVPanel
	{
		private global::Gtk.Fixed fixed1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Graphs.MVPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Graphs.MVPanel";
			// Container child Graphs.MVPanel.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
